In [1]:
import math
import random
import numpy as np
import scipy
import scipy.io
import matplotlib.pyplot as plt
%matplotlib inline 

In [2]:
mnist = scipy.io.loadmat("./mnist_data/images.mat")

#print(mnist)

mnist_data = mnist["images"].reshape((784, 60000))

def visualize(data):
    fig = plt.figure(figsize=(6, 3.2))

    ax = fig.add_subplot(111)
    ax.set_title('colorMap')
    plt.imshow(data.reshape((28,28)))

    cax = fig.add_axes([0.12, 0.1, 0.78, 0.8])
    cax.get_xaxis().set_visible(False)
    cax.get_yaxis().set_visible(False)
    cax.patch.set_alpha(0)
    cax.set_frame_on(False)
    plt.colorbar(orientation='vertical')
    plt.show()
    
#visualize(mnist_data[50000])
#visualize(mnist_data[50001])
#visualize(mnist_data[30001])

In [14]:
x = np.array([[1,2]])
print(x.shape)
y = np.repeat(x, [784], axis=0)
print(y)

w = np.array([[0, 0, 0],
       [3, 3, 3],
       [6, 6, 6],
       [9, 9, 9]])
z = np.array([3, 0, 3])
print(w.shape)
print(z.shape)
print(w - z)

(1, 2)
[[1 2]
 [1 2]
 [1 2]
 ..., 
 [1 2]
 [1 2]
 [1 2]]
(4, 3)
(3,)
[[-3  0 -3]
 [ 0  3  0]
 [ 3  6  3]
 [ 6  9  6]]


In [70]:
def kMeans(data, k = 5, iterations = 10):
    #Initialize k number of means as k random points in the data
    means = []
    usedIndices = []
    dataT = np.transpose(data)
    for _ in range(k):
        while True:
            index = int(random.random() * len(data))
            if index not in usedIndices:
                usedIndices.append(index)
                #mean = np.array([data[index]])
                means.append(dataT[index])
                break
                
    for _ in range(iterations):            
        print(means)
        #Assign points to various means
        #First, for every mean, stack the mean vertically
        distArrays = []
        for mean in means:
            #print(dataT.shape)
            #stackedMeans = np.repeat(mean, [60000], axis=0)
            #signedDist = np.subtract(data, stackedMeans)
            signedDist = dataT - mean
            dist = np.square(signedDist)
            dist = np.sum(dist, axis=1)
            distArrays.append(dist)
            #dist = np.dot(np.transpose(signedDist), signedDist)
            #print(dist)  
        
        print(distArrays)
            
        #Reclassify the points by minimum distance
        newClusters = [[] for _ in range(k)]

        for dataIndex in range(len(dataT)):
            minIndex = -1
            minDist = 0
            for i in range(k):
                if minIndex == -1 or distArrays[i][dataIndex] < minDist:
                    minIndex = i
                    minDist = distArrays[i][dataIndex]
            newClusters[minIndex].append(dataIndex)

        print(newClusters)    
            
        oldMean = means[0]    
            
        #Recalculate the means based on the newly generated clusters
        means = []
        for newCluster in newClusters:
            #print(newCluster)
            mean = np.zeros(shape=(3,))
            for dataIndex in newCluster:
                dataPoint = dataT[dataIndex]
                mean = np.add(mean, dataPoint)
            if len(newCluster) == 0:
                pass
            else:
                mean = np.dot(mean, 1.0/(len(newCluster)))
            #print(len(newCluster))
            means.append(mean)
    
        print(means)
    
        print(np.subtract(means[0], oldMean))
    
        print("------")
    
    return means
    
#kMeans(mnist_data, 5, 10)

x = np.array([[1,2,3],[4,5,6],[1,2,4],[5,6,7],[100,100,100],[100,101,100]])
#print(mnist_data.shape)
x = np.transpose(x)
#print(x.shape)

kMeans(x, 3, 10)


[array([1, 2, 4]), array([4, 5, 6]), array([1, 2, 3])]
[array([    1,    22,     0,    41, 28621, 28818], dtype=int32), array([   27,     0,    22,     3, 27077, 27268], dtype=int32), array([    0,    27,     1,    48, 28814, 29011], dtype=int32)]
[[2], [1, 3, 4, 5], [0]]
[array([ 1.,  2.,  4.]), array([ 52.25,  53.  ,  53.25]), array([ 1.,  2.,  3.])]
[ 0.  0.  0.]
------
[array([ 1.,  2.,  4.]), array([ 52.25,  53.  ,  53.25]), array([ 1.,  2.,  3.])]
[array([  1.00000000e+00,   2.20000000e+01,   0.00000000e+00,
         4.10000000e+01,   2.86210000e+04,   2.88180000e+04]), array([ 7752.625,  6864.625,  7653.125,  6580.625,  6674.625,  6769.625]), array([  0.00000000e+00,   2.70000000e+01,   1.00000000e+00,
         4.80000000e+01,   2.88140000e+04,   2.90110000e+04])]
[[1, 2, 3], [4, 5], [0]]
[array([ 3.33333333,  4.33333333,  5.66666667]), array([ 100. ,  100.5,  100. ]), array([ 1.,  2.,  3.])]
[ 2.33333333  2.33333333  1.66666667]
------
[array([ 3.33333333,  4.33333333,  5.66666

[array([ 4.5,  5.5,  6.5]),
 array([ 100. ,  100.5,  100. ]),
 array([ 1. ,  2. ,  3.5])]